version: '2'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: datos
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - db:/var/lib/mysql
        restart: always

    app:
        build: .
        ports:
           - 9999:80
        restart: always
        depends_on:
           - db
volumes:
   db:
